/* Original procedural vector side views. No photos, external models or WebGL required. */
(() => {
 'use strict';
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function garnish(type,y){
  if(!type)return '';
  if(['orange','lime','lemon','apple'].includes(type)){
   const colors={orange:['#e88523','#ffd482'],lime:['#688930','#e0e898'],lemon:['#d8b736','#f8edab'],apple:['#bb5860','#f6d7b4']},[a,b]=colors[type];
   return `<g class="drink-garnish" style="--float:-5px"><g transform="translate(276 ${y-11}) rotate(-22)"><circle r="35" fill="${a}"/><circle r="30" fill="${b}"/><circle r="3" fill="${a}"/>${Array.from({length:type==='apple'?3:8},(_,i)=>`<path d="M0 0 L0 -29" stroke="${a}" stroke-width="1.5" transform="rotate(${i*45})" opacity=".7"/>`).join('')}</g></g>`;
  }
  if(type==='mint'||type==='grape')return `<g class="drink-garnish" style="--float:-5px" transform="translate(254 ${y-8})"><path d="M0 20Q-2 -6 18 -37" fill="none" stroke="#466535" stroke-width="3"/>${[-1,1].map((s,i)=>`<ellipse cx="${s*14+8}" cy="${-i*20}" rx="13" ry="24" transform="rotate(${s*40} ${s*14+8} ${-i*20})" fill="${i?'#769854':'#9fb55f'}" stroke="#c5d688" stroke-width="1"/>`).join('')}${type==='grape'?'<circle cx="18" cy="17" r="12" fill="#c2cf7c"/><circle cx="-3" cy="20" r="11" fill="#a9c56f"/>':''}</g>`;
  if(type==='cherry')return `<g class="drink-garnish" style="--float:-3px"><path d="M244 ${y+9} Q262 ${y-30} 292 ${y-35}" fill="none" stroke="#ad9c56" stroke-width="2"/><circle cx="243" cy="${y+12}" r="13" fill="#923042"/><ellipse cx="238" cy="${y+7}" rx="4" ry="3" fill="#ec8c93"/></g>`;
  if(type==='twist')return `<path class="drink-garnish" d="M247 ${y-15} C205 ${y-55} 282 ${y-62} 271 ${y-15} S220 ${y+30} 211 ${y+5}" fill="none" stroke="#edaa47" stroke-width="13" stroke-linecap="butt"/>`;
  const color={zest:'#648b35',matcha:'#48682a',cocoa:'#5f3525',sesame:'#302c25',tea:'#91411f',osmanthus:'#d89931',pistachio:'#739242',flower:'#f6f0c8'}[type]||'#835b32';
  return `<g class="drink-topping">${Array.from({length:19},(_,i)=>{const x=168+(i*37%102),yy=y-5+(i*17%17)-8;return `<ellipse cx="${x}" cy="${yy}" rx="${type==='sesame'?2:2+i%3}" ry="${type==='sesame'?1.1:1.6}" transform="rotate(${i*43} ${x} ${yy})" fill="${color}"/>`}).join('')}</g>`;
 }
 window.renderDrinkArt=function(d){
  const uid=`art-${d.id}`,stem=d.glass==='martini',tall=d.glass==='tall',ceramic=d.glass==='ceramic';
  const top=stem?154:tall?100:174,bottom=stem?283:416,w=stem?122:tall?75:105,cx=220;
  const left=cx-w,right=cx+w,baseW=stem?8:ceramic?83:d.glass==='waist'?87:w-9;
  const body=stem?`M${left} ${top} Q${cx} ${top+24} ${right} ${top} L${cx+8} ${bottom} Q${cx} ${bottom+5} ${cx-8} ${bottom} Z`:d.glass==='waist'?`M${left} ${top} L${left+7} ${bottom-120} Q${left+21} ${bottom-104} ${left+18} ${bottom-82} L${cx-baseW} ${bottom} Q${cx} ${bottom+19} ${cx+baseW} ${bottom} L${right-18} ${bottom-82} Q${right-21} ${bottom-104} ${right-7} ${bottom-120} L${right} ${top} Z`:`M${left} ${top} L${cx-baseW} ${bottom} Q${cx} ${bottom+18} ${cx+baseW} ${bottom} L${right} ${top} Z`;
  const liquidBottom=stem?bottom:bottom-9,liquidTop=top+(stem?26:19),height=liquidBottom-liquidTop;
  let cursor=liquidBottom;
  const layers=d.layers.map((l,i)=>{const h=height*l.weight,y=cursor-h;cursor=y;return {...l,i,y,h};});
  const ids=d.layers.map((_,i)=>`${uid}-layer-${i}`);
  const defs=layers.map((l,i)=>`<linearGradient id="${ids[i]}" x1="0" y1="0" x2="1" y2=".1"><stop stop-color="${l.color}"/><stop offset=".48" stop-color="${l.color}"/><stop offset="1" stop-color="${l.color}" stop-opacity=".73"/></linearGradient>`).join('');
  const liquid=layers.map((l,i)=>`<g class="liquid-layer" data-layer="${i}" style="--lift:${-(i+1)*30}px;--delay:${i*.08}s"><g clip-path="url(#${uid}-clip)"><path class="liquid-fill" data-y="${l.y}" data-height="${l.h}" data-phase="${i}" d="M70 ${l.y} Q220 ${l.y+14} 370 ${l.y} V${l.y+l.h+15} H70 Z" fill="url(#${ids[i]})"/><ellipse class="liquid-surface" cx="220" cy="${l.y}" rx="${w-3}" ry="${stem?8:12}" fill="${l.color}" stroke="#fff4d9" stroke-opacity=".35" stroke-width="1"/></g></g>`).join('');
  const iceY=d.layers.length>1?layers[layers.length-1].y+40:liquidTop+53;
  const ice=Array.from({length:d.ice||0},(_,i)=>{const size=d.ice===1?75:43,x=d.ice===1?cx-38:cx-50+(i%2)*55,y=Math.min(bottom-size-18,iceY+i*44);return `<g class="ice-float" style="--delay:${i*-.7}s;--float:${i%2?'-7px':'6px'};--turn:${i%2?'7deg':'-6deg'}"><g transform="translate(${x} ${y}) rotate(${i%2?16:-12} ${size/2} ${size/2})"><rect width="${size}" height="${size}" rx="9" fill="url(#${uid}-ice)" stroke="#fff" stroke-opacity=".58"/><path d="M8 ${size-10} V8 H${size-12} M${size-8} 12 L${size-18} 22" fill="none" stroke="#fff" stroke-opacity=".68" stroke-width="2"/></g></g>`}).join('');
  const bubbles=d.fizz?Array.from({length:18},(_,i)=>`<circle class="drink-bubble" cx="${cx-w+15+(i*31%(w*2-30))}" cy="${bottom-18}" r="${1.6+i%4}" fill="none" stroke="#fff7d9" stroke-width="1" style="--rise:${-(height-38)}px;--delay:${-i*.6}s;--duration:${3+i%3}s"/>`).join(''):'';
  const handle=d.glass==='handle'?`<path d="M${right-2} ${top+39} C${right+78} ${top+11} ${right+80} ${bottom-61} ${right-7} ${bottom-55}" fill="none" stroke="#c69551" stroke-width="18" stroke-opacity=".6"/><path d="M${right} ${top+36} C${right+66} ${top+19} ${right+67} ${bottom-67} ${right-5} ${bottom-62}" fill="none" stroke="#ffe2a4" stroke-width="2"/>`:ceramic?`<path d="M${right-2} ${top+36} H${right+44} V${bottom-58} H${right-17}" fill="none" stroke="#98633c" stroke-width="19" stroke-linejoin="round"/><ellipse cx="220" cy="${bottom+11}" rx="113" ry="19" fill="#a5734d"/><path d="M116 ${bottom+12} Q220 ${bottom+34} 324 ${bottom+12}" fill="none" stroke="#c39365" stroke-width="3"/>`:'';
  const glass=`${stem?`<path d="M220 ${bottom+5} V421" stroke="url(#${uid}-glass)" stroke-width="9"/><ellipse cx="220" cy="427" rx="69" ry="12" fill="url(#${uid}-glass)" stroke="currentColor" stroke-opacity=".35"/>`:''}<path d="${body}" fill="url(#${uid}-glass)" stroke="${ceramic?'#eee0c3':'currentColor'}" stroke-opacity=".55" stroke-width="${ceramic?4:1.5}"/><ellipse cx="220" cy="${top}" rx="${w}" ry="13" fill="none" stroke="currentColor" stroke-opacity=".5" stroke-width="1.3"/><ellipse cx="220" cy="${top}" rx="${w-4}" ry="10" fill="none" stroke="#fff9e7" stroke-opacity=".7"/><path d="M${left+8} ${top+27} L${cx-baseW+9} ${bottom-8}" stroke="#fff" stroke-opacity=".60" stroke-width="4" fill="none" stroke-linecap="round"/><path d="M${right-9} ${top+43} L${cx+baseW-8} ${bottom-17}" stroke="#fff" stroke-opacity=".2" stroke-width="8" fill="none"/>`;
  const ceramicShell=ceramic?`<path class="ceramic-shell" d="${body}" fill="#e7dec6"/><ellipse class="ceramic-shell" cx="220" cy="${liquidTop}" rx="${w-5}" ry="12" fill="${layers.at(-1).color}"/>`:'';
  return `<svg class="drink-illustration ${d.category}-illustration ${d.layers.length>1?'layered-drink':'single-drink'}" viewBox="0 0 460 490" role="img" aria-label="${esc(d.name)}的几何侧视图" xmlns="http://www.w3.org/2000/svg"><defs><clipPath id="${uid}-clip"><path d="${body}"/></clipPath>${defs}<linearGradient id="${uid}-glass"><stop stop-color="#fff" stop-opacity=".15"/><stop offset=".15" stop-color="#fff" stop-opacity=".03"/><stop offset=".8" stop-color="#fff" stop-opacity="0"/><stop offset="1" stop-color="#fff" stop-opacity=".28"/></linearGradient><linearGradient id="${uid}-ice" x2=".8" y2="1"><stop stop-color="#fff" stop-opacity=".45"/><stop offset=".6" stop-color="#ecfcff" stop-opacity=".08"/><stop offset="1" stop-color="#fff" stop-opacity=".32"/></linearGradient></defs><ellipse class="drink-shadow" cx="220" cy="447" rx="${stem?91:118}" ry="11" fill="currentColor" opacity=".08"/><g class="drink-object">${handle}<g class="drink-liquid">${liquid}</g><g class="drink-ice" clip-path="url(#${uid}-clip)">${ice}${bubbles}</g>${ceramicShell}<g class="drink-glass">${glass}</g><g class="glass-light" clip-path="url(#${uid}-clip)"><path class="glass-shimmer" d="M-140 10 H-112 L98 480 H70 Z" fill="#fff8dc" opacity=".28"/><path class="glass-shimmer fine-shimmer" d="M-105 10 H-100 L110 480 H105 Z" fill="#ffffff" opacity=".65"/></g><g class="garnish-lift" style="--lift:${-d.layers.length*30}px">${garnish(d.garnish,liquidTop)}</g></g></svg>`;
 };
})();
